from custom_classes import *

scilla = Item(name='Scilla', cost=10, weight=0, sprite=541, flavor_text='A lovely blue flower.')
rose = Item(name='Rose', cost=10, weight=0, sprite=542, flavor_text='Not as red as you expected.')
violet = Item(name='Violet', cost=10, weight=0, sprite=543, flavor_text='Roses are red, violets are blue, I hit my head, there once was a man from peru')
camellia = Item(name='Camellia', cost=10, weight=0, sprite=544, flavor_text='Snow on mount Fuji')
sapphire = Item(name='Sapphire', cost=200, weight=1, sprite=546, flavor_text='Have a bite!')
garnet = Item(name='Garnet', cost=600, weight=1, sprite=547)
amber = Item(name='Amber', cost=2000, weight=1, sprite=548)
tigerseye = Item(name="Tiger's Eye", cost=10000, weight=1, sprite=549, flavor_text="That's just a couple of pixels why is it worth so much?")
chest = Item(name='Small Chest', cost=50, weight=5, sprite=550)
rmush = Item(name='Red Mushroom', cost=10, weight=1, sprite=162)
lmush = Item(name='Large Red Mushroom', cost=20, weight=2, sprite=219)
smush = Item(name='Spotted Mushroom', cost=40, weight=1, sprite=276)
lsmush = Item(name='Large Spotted Mushroom', cost=80, weight=1, sprite=333)
bmush = Item(name='Brown Mushroom', cost=5, weight=1, sprite=390)
lbmush = Item(name='Large Brown Mushroom', cost=10, weight=2, sprite=447)
redbottle = Item(name='Red Bottle', cost=20, weight=2, sprite=682)
yellowbottle = Item(name='Yellow Bottle', cost=20, weight=2, sprite=683)
bluebottle = Item(name='Blue Bottle', cost=20, weight=2, sprite=738)
greenbottle = Item(name='Green Bottle', cost=20, weight=2, sprite=852)
book = Item(name='Book', cost=200, weight=1, sprite=901, flavor_text='Man I wish I learned how to read.')
bible = Item(name='Religious Text', cost=400, weight=1, sprite=902)
novel = Item(name='Novel', cost=20, weight=2, sprite=903)
oldbook = Item(name='Historical Document', cost=8000, weight=1, sprite=904)
paper = Item(name='Parchment', cost=2, weight=0, sprite=896)
document = Item(name='Document', cost=8, weight=0, sprite=897)
scroll = Item(name='Scroll', cost=60, weight=0, sprite=899)

floatingtestone = EquipmentItem(name='Floating Test One', cost=0, weight=0, sprite=562)

gauntlet = Weapon(name='Gauntlet', dmg='1d3', dmg_style='Bludgeoning', weight=1, weapon_type='simple', cost=2, handed=1, crit_mult='x2', dmg_range=0, weap_id=0)

dagger = Weapon(name='Dagger', dmg='1d4', dmg_style='Piercing or slashing', weight=1, weapon_type='simple', cost=2, handed=1, crit_mult='19-20/x2', dmg_range=10, weap_id=0)
spikedGauntlet = Weapon(name='Spiked Gauntlet', dmg='1d4', dmg_style='Piercing', weight=1, weapon_type='simple', cost=5, handed=1, crit_mult='x2', dmg_range=0, weap_id=1)
lightmace = Weapon(name='Light Mace', dmg='1d6', dmg_style='Bludgeoning', weight=4, weapon_type='simple', cost=5, handed=1, crit_mult='x2', dmg_range=0, weap_id=2)
sickle = Weapon(name='Sickle', dmg='1d6', dmg_style='Slashing', weight=2, weapon_type='simple', cost=6, handed=1, crit_mult='x2', dmg_range=0, weap_id=3)
club = Weapon(name='Club', dmg='1d6', dmg_style='Bludgeoning', weight=3, weapon_type='simple', cost=0, handed=1, crit_mult='x2', dmg_range=10, weap_id=4)
hevaymace = Weapon(name='Heavy Mace', dmg='1d8', dmg_style='Bludgeoning', weight=8, weapon_type='simple', cost=12, handed=1, crit_mult='x2', dmg_range=0, weap_id=5)
morningstar = Weapon(name='Morningstar', dmg='1d8', dmg_style='Bludgeoning and piercing', weight=6, weapon_type='simple', cost=8, handed=1, crit_mult='x2', dmg_range=0, weap_id=6)
shortspear = Weapon(name='Short Spear', dmg='1d6', dmg_style='Piercing', weight=3, weapon_type='simple', cost=1, handed=1, crit_mult='x2', dmg_range=20, weap_id=7)
longspear = Weapon(name='Long Spear', dmg='1d8', dmg_style='Piercing', weight=9, weapon_type='simple', cost=5, handed=2, crit_mult='x3', dmg_range=0, weap_id=8)
quarterstaff = Weapon(name='Quarterstaff', dmg='1d6/1d6', dmg_style='Bludgeoning', weight=4, weapon_type='simple', cost=0, handed=2, crit_mult='x2', dmg_range=0, weap_id=9)
throwingaxe = Weapon(name='Throwing Axe', dmg='1d6', dmg_style='Slashing', weight=2, weapon_type='martial', cost=8, handed=2, crit_mult='x2', dmg_range=10, weap_id=10)
lighthammer = Weapon(name='Light Hammer', dmg='1d4', dmg_style='Bludgeoning', weight=2, weapon_type='martial', cost=1, handed=1, crit_mult='x2', dmg_range=20, weap_id=11)
handaxe = Weapon(name='Hand Axe', dmg='1d6', dmg_style='Slashing', weight=3, weapon_type='martial', cost=6, handed=1, crit_mult='x3', dmg_range=0, weap_id=12)
kukri = Weapon(name='Kukri', dmg='1d4', dmg_style='Slashing', weight=2, weapon_type='martial', cost=8, handed=1, crit_mult='18-20/x2', dmg_range=0, weap_id=13)
lightPick = Weapon(name='Light Pick', dmg='1d4', dmg_style='Piercing', weight=3, weapon_type='martial', cost=4, handed=1, crit_mult='x4', dmg_range=0, weap_id=14)
shortsword = Weapon(name='Short Sword', dmg='1d6', dmg_style='Piercing', weight=2, weapon_type='martial', cost=10, handed=1, crit_mult='19-20/x2', dmg_range=0, weap_id=15)
battleaxe = Weapon(name='Battle Axe', dmg='1d8', dmg_style='Slashing', weight=6, weapon_type='martial', cost=10, handed=1, crit_mult='x3', dmg_range=0, weap_id=16)
flail = Weapon(name='Flail', dmg='1d8', dmg_style='Bludgeoning', weight=5, weapon_type='martial', cost=8, handed=1, crit_mult='x2', dmg_range=0, weap_id=17)
longsword = Weapon(name='Long Sword', dmg='1d8', dmg_style='Slashing', weight=4, weapon_type='martial', cost=15, handed=1, crit_mult='19-20/x2', dmg_range=0, weap_id=18)
heavypick = Weapon(name='Heavy Pick', dmg='1d6', dmg_style='Piercing', weight=6, weapon_type='martial', cost=8, handed=1, crit_mult='x4', dmg_range=0, weap_id=19)
rapier = Weapon(name='Rapier', dmg='1d6', dmg_style='Piercing', weight=2, weapon_type='martial', cost=20, handed=1, crit_mult='18-20/x2', dmg_range=0, weap_id=20)
scimitar = Weapon(name='Scimitar', dmg='1d6', dmg_style='Slashing', weight=4, weapon_type='martial', cost=15, handed=1, crit_mult='18-20/x2', dmg_range=0, weap_id=21)
trident = Weapon(name='Trident', dmg='1d8', dmg_style='Piercing', weight=4, weapon_type='martial', cost=15, handed=1, crit_mult='x2', dmg_range=10, weap_id=22)
warhammer = Weapon(name='War Hammer', dmg='1d8', dmg_style='Bludgeoning', weight=5, weapon_type='martial', cost=12, handed=1, crit_mult='3', dmg_range=0, weap_id=23)
falchion = Weapon(name='Falchion', dmg='2d4', dmg_style='Slashing', weight=8, weapon_type='martial', cost=75, handed=2, crit_mult='18-20/x2', dmg_range=0, weap_id=24)
glaive = Weapon(name='Glaive', dmg='1d10', dmg_style='Slashing', weight=10, weapon_type='martial', cost=8, handed=2, crit_mult='x3', dmg_range=0, weap_id=25)
greataxe = Weapon(name='Great Axe', dmg='1d12', dmg_style='Slashing', weight=12, weapon_type='martial', cost=20, handed=2, crit_mult='x3', dmg_range=0, weap_id=26)
greatclub = Weapon(name='Great Club', dmg='1d10', dmg_style='Bludgeoning', weight=8, weapon_type='martial', cost=5, handed=2, crit_mult='x2', dmg_range=0, weap_id=27)
heavyflail = Weapon(name='Heavy Flail', dmg='1d10', dmg_style='Bludgeoning', weight=10, weapon_type='martial', cost=15, handed=2, crit_mult='19-20/x2', dmg_range=0, weap_id=28)
greatsword = Weapon(name='Great Sword', dmg='2d6', dmg_style='Slashing', weight=8, weapon_type='martial', cost=50, handed=2, crit_mult='19-20/x2', dmg_range=0, weap_id=29)
guisarme = Weapon(name='Guisarme', dmg='2d4', dmg_style='Slashing', weight=12, weapon_type='martial', cost=9, handed=2, crit_mult='x3', dmg_range=0, weap_id=30)
halberd = Weapon(name='Halberd', dmg='1d10', dmg_style='Piercing or slashing', weight=12, weapon_type='martial', cost=10, handed=2, crit_mult='x3', dmg_range=0, weap_id=31)
lance = Weapon(name='Lance', dmg='1d8', dmg_style='Piercing', weight=10, weapon_type='martial', cost=10, handed=2, crit_mult='x3', dmg_range=0, weap_id=32)
ranseur = Weapon(name='Ranseur', dmg='2d4', dmg_style='Piercing', weight=12, weapon_type='martial', cost=10, handed=2, crit_mult='x3', dmg_range=0, weap_id=33)
scythe = Weapon(name='Scythe', dmg='2d4', dmg_style='Piercing or slashing', weight=10, weapon_type='martial', cost=18, handed=2, crit_mult='x4', dmg_range=0, weap_id=34)
kama = Weapon(name='Kama', dmg='1d6', dmg_style='Slashing', weight=2, weapon_type='exotic', cost=2, handed=1, crit_mult='x2', dmg_range=0, weap_id=35)
nunchaku = Weapon(name='Nunchaku', dmg='1d6', dmg_style='Bludgeoning', weight=2, weapon_type='exotic', cost=2, handed=1, crit_mult='x2', dmg_range=0, weap_id=36)
sai = Weapon(name='Sai', dmg='1d4', dmg_style='Bludgeoning', weight=1, weapon_type='exotic', cost=1, handed=1, crit_mult='x2', dmg_range=10, weap_id=37)
siangham = Weapon(name='Siangham', dmg='1d6', dmg_style='Piercing', weight=1, weapon_type='exotic', cost=3, handed=1, crit_mult='x2', dmg_range=0, weap_id=38)
bastardsword = Weapon(name='Bastard Sword', dmg='1d10', dmg_style='Slashing', weight=6, weapon_type='exotic', cost=35, handed=1, crit_mult='19-20/x2', dmg_range=0, weap_id=39)
dwarvenwaraxe = Weapon(name='Dwarven Waraxe', dmg='1d10', dmg_style='Slashing', weight=8, weapon_type='exotic', cost=30, handed=1, crit_mult='x3', dmg_range=0, weap_id=40)
orcdoubleaxe = Weapon(name='Orc Double Axe', dmg='1d8/1d8', dmg_style='Slashing', weight=15, weapon_type='exotic', cost=60, handed=2, crit_mult='x3', dmg_range=0, weap_id=41)
spikedchain = Weapon(name='Spiked Chain', dmg='2d4', dmg_style='Piercing', weight=10, weapon_type='exotic', cost=25, handed=2, crit_mult='x2', dmg_range=0, weap_id=42)
direflail = Weapon(name='Dire Flail', dmg='1d8/1d8', dmg_style='Bludgeoning', weight=10, weapon_type='exotic', cost=90, handed=2, crit_mult='x2', dmg_range=0, weap_id=43)
gnomehookedhammer = Weapon(name='Gnome Hooked Hammer', dmg='1d8/1d6', dmg_style='Bludgeoning/Piercing', weight=6, weapon_type='exotic', cost=20, handed=2, crit_mult='x3/x4', dmg_range=0, weap_id=44)
twobladedsword = Weapon(name='Two Bladed Sword', dmg='1d8/1d8', dmg_style='Slashing', weight=10, weapon_type='exotic', cost=100, handed=2, crit_mult='19-20/x2', dmg_range=0, weap_id=45)
dwarvenurgrosh = Weapon(name='Dwarven Urgrosh', dmg='1d8/1d6', dmg_style='Slashing or piercing', weight=12, weapon_type='exotic', cost=50, handed=2, crit_mult='x3', dmg_range=0, weap_id=46)
bolas = Weapon(name='Bolas', dmg='1d4', dmg_style='Bludgeoning', weight=2, weapon_type='exotic', cost=5, handed=2, crit_mult='x2', dmg_range=10, weap_id=47)


lightcrossbow = Weapon(name='Light Crossbow', dmg='1d8', dmg_style='Piercing', weight=4, weapon_type='simple', cost=35, handed=2, crit_mult='19-20/x2', dmg_range=80, weap_id=1813)
heavycrossbow = Weapon(name='Heavy Crossbow', dmg='1d10', dmg_style='Piercing', weight=8, weapon_type='simple', cost=50, handed=2, crit_mult='19-20/x2', dmg_range=120, weap_id=1870)
dart = Weapon(name='Dart', dmg='1d4', dmg_style='Piercing', weight=1, weapon_type='simple', cost=5, handed=2, crit_mult='x2', dmg_range=20, weap_id=0)
javelin = Weapon(name='Javelin', dmg='1d6', dmg_style='Piercing', weight=2, weapon_type='simple', cost=1, handed=2, crit_mult='x2', dmg_range=30, weap_id=2038)
longbow = Weapon(name='Longbow', dmg='1d8', dmg_style='Piercing', weight=3, weapon_type='martial', cost=75, handed=2, crit_mult='x3', dmg_range=100, weap_id=1928)
compositelongbow = Weapon(name='Composite Longbow', dmg='1d8', dmg_style='Piercing', weight=3, weapon_type='martial', cost=100, handed=2, crit_mult='x3', dmg_range=110, weap_id=0)
shortbow = Weapon(name='Shortbow', dmg='1d6', dmg_style='Piercing', weight=2, weapon_type='martial', cost=30, handed=2, crit_mult='x3', dmg_range=60, weap_id=1813)
compositeshortbow = Weapon(name='Composite Shortbow', dmg='1d6', dmg_style='Piercing', weight=2, weapon_type='martial', cost=75, handed=2, crit_mult='x3', dmg_range=70, weap_id=0)
handcrossbow = Weapon(name='Hand Crossbow', dmg='1d4', dmg_style='Piercing', weight=2, weapon_type='exotic', cost=100, handed=2, crit_mult='19-20/x2', dmg_range=30, weap_id=0)
repeatingheavycrossbow = Weapon(name='Repeating Heavy Crossbow', dmg='1d10', dmg_style='Piercing', weight=12, weapon_type='exotic', cost=400, handed=2, crit_mult='19-20/x2', dmg_range=120, weap_id=0)
lightrepeatingcrossbow = Weapon(name='Light Repeating Crossbow', dmg='1d8', dmg_style='Piercing', weight=6, weapon_type='exotic', cost=250, handed=2, crit_mult='19-20/x2', dmg_range=80, weap_id=0)


sling = Weapon(name='Sling', dmg='1d4', dmg_style='Bludgeoning', weight=0, weapon_type='simple', cost=0, handed=2, crit_mult='x2', dmg_range=50, weap_id=0)
sap = Weapon(name='Sap', dmg='1d6', dmg_style='Bludgeoning', weight=2, weapon_type='martial', cost=1, handed=1, crit_mult='x2', dmg_range=0, weap_id=0)
whip = Weapon(name='Whip', dmg='1d3', dmg_style='Slashing', weight=2, weapon_type='exotic', cost=1, handed=1, crit_mult='x2', dmg_range=0, weap_id=0)


padded = Armor(name='Padded', weight=10, speed=30, asfc=5, armor_type='light', bonus=1, acp=0, cost=5, max_bonus=8, sprite=2289)
leather = Armor(name='Leather', weight=15, speed=30, asfc=10, armor_type='light', bonus=2, acp=0, cost=10, max_bonus=6, sprite=2000)
studdedleather = Armor(name='Studded leather', weight=20, speed=30, asfc=15, armor_type='light', bonus=3, acp=-1, cost=25, max_bonus=5, sprite=1999)
chainshirt = Armor(name='Chainshirt', weight=25, speed=30, asfc=20, armor_type='light', bonus=4, acp=-2, cost=100, max_bonus=4, sprite=2003)
hide = Armor(name='Hide', weight=25, speed=20, asfc=20, armor_type='medium', bonus=3, acp=-3, cost=15, max_bonus=4, sprite=2004)
scalemail = Armor(name='Scalemail', weight=30, speed=20, asfc=25, armor_type='medium', bonus=4, acp=-4, cost=50, max_bonus=3, sprite=2285)
chainmail = Armor(name='Chainmail', weight=40, speed=20, asfc=30, armor_type='medium', bonus=5, acp=-5, cost=150, max_bonus=2, sprite=2005)
breastplate = Armor(name='Breastplate', weight=30, speed=20, asfc=25, armor_type='medium', bonus=5, acp=-4, cost=200, max_bonus=3, sprite=0)
splintmail = Armor(name='Splintmail', weight=45, speed=20, asfc=40, armor_type='heavy', bonus=6, acp=-7, cost=200, max_bonus=0, sprite=2292)
bandedmail = Armor(name='Bandedmail', weight=35, speed=20, asfc=35, armor_type='heavy', bonus=6, acp=-6, cost=250, max_bonus=1, sprite=2008)
halfplate = Armor(name='Halfplate', weight=50, speed=20, asfc=40, armor_type='heavy', bonus=7, acp=-7, cost=600, max_bonus=0, sprite=0)
fullplate = Armor(name='Fullplate', weight=50, speed=20, asfc=35, armor_type='heavy', bonus=8, acp=-6, cost=500, max_bonus=1, sprite=0)
buckler = Armor(name='Buckler', weight=5, speed=0, asfc=5, armor_type='shield', bonus=1, acp=-1, cost=15, max_bonus=0, sprite=1795)
lightwoodenslield = Armor(name='Light Wooden Shield', weight=5, speed=0, asfc=5, armor_type='shield', bonus=1, acp=-1, cost=3, max_bonus=0, sprite=1796)
lightsteelshield = Armor(name='Light Steel Shield', weight=6, speed=0, asfc=5, armor_type='shield', bonus=1, acp=-1, cost=9, max_bonus=0, sprite=1801)
heavywoodenshield = Armor(name='Heavy Wooden Shield', weight=10, speed=0, asfc=15, armor_type='shield', bonus=2, acp=-2, cost=7, max_bonus=0, sprite=1853)
heavysteelshield = Armor(name='Heavy Steel Shield', weight=15, speed=0, asfc=15, armor_type='shield', bonus=2, acp=-2, cost=20, max_bonus=0, sprite=1914)
towershield = Armor(name='Tower Shield', weight=45, speed=0, asfc=50, armor_type='shield', bonus=4, acp=-10, cost=30, max_bonus=2, sprite=1798)
